# Generated by Django 3.1.1 on 2020-12-24 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201223_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.question')),
                ('Name', models.CharField(max_length=100)),
                ('Semester', models.IntegerField()),
                ('Section', models.CharField(max_length=1)),
            ],
        ),
    ]
