# Generated by Django 3.1.1 on 2020-12-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Quiz',
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.question'),
        ),
    ]
