# Generated by Django 3.1.1 on 2020-12-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201224_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Name',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='Section',
            field=models.CharField(default='--', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='Semester',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
