# Generated by Django 3.1.1 on 2020-12-24 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20201224_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Semester',
        ),
    ]
